api/urls.py
from django.conf.urls import patterns, include, url

from actividades import views

urlpatterns = patterns(
    '',
    url(r'^niveles/', include('niveles.urls', namespace='niveles')),
)

funnyd/urls.py
from django.conf import settings
from django.conf.urls import url, include
from django.conf.urls.static import static
from django.contrib import admin

# from niveles.views import IntentoAPI

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url('', include('app.urls')),
    url('', include('admon.urls')),
    url('', include('actividades.urls')),
    url(r'^api/', include('api.urls', namespace='api')),
    # url(r'^api/niveles/save/$', IntentoAPI.as_view(), name='niveles_save'),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

usuarios/models.py
# coding=utf-8
from __future__ import unicode_literals

import datetime
from django.db import models
from django.contrib.auth.models import User

# Lista "ENUM" para genero
GENEROS = (
    ('M', 'Masculino'),
    ('F', 'Femenino'),
)


# Modelo de usuarios del sistema
class usuariosModel(models.Model):
    class Meta:
        verbose_name = 'Usuario'
        verbose_name_plural = 'Usuarios'

    user = models.OneToOneField(User)
    slug = models.SlugField()
    documento = models.CharField(null=True, blank=True, max_length=15)
    genero = models.CharField(max_length=2, choices=GENEROS, null=False, blank=False)
    fnacimiento = models.DateField()

    @property
    def edad(self):
        diff = (datetime.date.today() - self.fnacimiento).days
        years = str(int(diff / 365))
        return years + ' años'
    # retorna nombre de usuario
    def __str__(self):
        return u'%s' % (self.user)

    def __unicode__(self):
        return u'%s' % (self.user)

app/templates/cambiocontrasenia.html
{% extends "app/base.html" %}
{% load staticfiles %}
{% load static %}
{% block menu %}
	<nav class="navbar navbar-embossed menu-nav row middle" style="background-color: #FEFB64">
		<div class="col-4">
			<div class="fuente">Cambio de Contraseña</div>
		</div>
		<div class="botonbarranav">
			<a class="btn btn-primary btn-lg btn-block" style="color: #000000" href="{% url 'admon_ingresar' %}">Ingreso</a>
		</div>
	</nav>
{% endblock menu %}
{% block  content %}

	<div class="login-form" style="background-color: #FFFFFF">
        <form action="." method="post">
            {% csrf_token %}
            <div class="form-group">
                <div class="fuente fuente-form"> Recuerda Tu Contraseña</div>
            </div>

            <div class="form-group">
              <input type="text" class="form-control login-field" value="" placeholder="Usuario" id="login-usuario" name="login-usuario">
              <label class="login-field-icon fui-user" for="login-name"></label>
            </div>

            <div class="form-group">
              <input type="text" class="form-control login-field" value="" placeholder="Identificación" id="login-identificacion" name="login-identificacion">
              <label class="login-field-icon fui-credit-card" for="login-name"></label>
            </div>

            <div class="form-group">
              <input type="password" class="form-control login-field" value="" placeholder="Nueva Contraseña" id="login-pass" name="login-pass">
              <label class="login-field-icon fui-lock" for="login-pass"></label>
            </div>

            <div class="form-group">
                <input type="password" class="form-control login-field" value="" placeholder="Ingresa de nuevo tu contraseña" id="login-pass2" name="login-pass2">
                <label class="login-field-icon fui-lock" for="login-pass"></label>
            </div>

            <div class="form-group" style="text-align: right">
                <button type="submit" class="btn btn-primary btn-lg btn-block" href="#" style="margin-right: 43px; color: #000000; background-color:#FFFF99">Cambiar</button>
            </div>
        </form>
  </div>
   <div id="backgroundaudio">
        <i class="fa fa-volume-up"></i>
        <audio autoplay="" controls="" loop="" preload="">
            <source src="{% static "../m.mp3" %}" type="audio/mpeg"/>
            Your browser does not support the audio element.
        </audio>
    </div>

{% endblock  %}

app/templates/inicio.html
{% extends "app/base.html" %}
{% load staticfiles %}
{% load static %}
{% block menu %}
    <nav class="navbar navbar-embossed menu-nav row middle" style="background-color: #ffa382!important;">
        <div class="col-4">
            <div class="fuente">
                funnYD
            </div>
        </div>
        <div class="col-5">
        </div>
        <div class="col-1">
            <a href="{% url 'registro' %}" class="btn btn-primary" style="background-color: #FFFF99; color: black;">Registro</a>
        </div>
        <div class="col-1">
            <a href="{% url 'admon_ingresar' %}" class="btn btn-primary" style="background-color: #66FF99; color: black;">Ingreso</a>

        </div>
    </nav>
{% endblock menu %}
{% block content %}

    <div class ="fuente fuente-paginicio" >
        Bienvenido a
        <img class ="actividad-image" src="static/img/inicio/logo.png" alt="" width="680px" height="350px">

    </div>
    <div id="backgroundaudio">
        <i class="fa fa-volume-up"></i>
        <audio autoplay="" controls="" loop="" preload="">
            <source src="{% static "../m.mp3" %}" type="audio/mpeg"/>
            Your browser does not support the audio element.
        </audio>
    </div>


{% endblock content %}

app/templates/menu_admon.html
<nav class="navbar navbar-embossed menu-nav row middle" style="background-color: #EBEBEB">
	<div class="col-4">
        <div class="fuente">
            funnYD
        </div>
        </div>
        <div class="col-7">
        </div>
        <div class="col-1">
            <a href="{% url 'logout' %}" class="btn btn-primary" style="background-color: #66FF99; color: black;">Salir</a>

        </div>
</nav>

app/templates/menu_inicio.html
<nav class="navbar navbar-embossed menu-nav row middle">
	<div class="col-4">
	<div class="fuente">
		funnYD
	</div>
	</div>
	<div class="col-5">
	</div>
	<div class="col-1">
        <a href="{% url 'admon_ingresar' %}" class="btn btn-primary">Ingresar</a>
    </div>
	<div class="col-1">
			<a href="{% url 'registro' %}" class="btn btn-primary">Registro</a>
	</div>
</nav>

app/templates/registro.html
{% extends "app/base.html" %}
{% load staticfiles %}
{% load static %}
{% block menu %}
    <nav style="background-color: #00C8F8" class="navbar navbar-embossed menu-nav row middle">
        <div class="col-10">
            <div class="fuente">Registro</div>
        </div>
       <div class="col-1">
            <a href="{% url 'admon_ingresar' %}" class="btn btn-primary" style="background-color: #66FF99; color: #000000; border: 1px solid #000000">Ingreso</a>
        </div>
            <div class="col-1">
                <a href="{% url 'inicio' %}" class="fuente"> Salir </a>
        </div>
    </nav>
{% endblock menu %}
{% block  content %}

    <div class = "login-form" style="background-color: #FFFFFF">
        <div class="form-group">
            <div class="fuente fuente-form">Registrate! </div>
        </div>
        <form action="." method="post" style="background-color: #FFFFFF">
            {% csrf_token %}
            <div class="form-group">
                <input type="text" class="form-control login-field" value="" placeholder="Usuario" id="id_username" name="username">
                <label class="login-field-icon fui-user" for="login-name"></label>
            </div>

            <div class="form-group">
                <input type="password" class="form-control login-field" value="" placeholder="Contraseña" id="id_password1" name="password1">
                <label class="login-field-icon fui-lock" for="login-pass"></label>
            </div>

            <div class="form-group">
                <input type="password" class="form-control login-field" value="" placeholder="Contraseña" id="id_password2" name="password2">
                <label class="login-field-icon fui-lock" for="login-pass"></label>
            </div>

            <div class="form-group">
                <input type="text" class="form-control login-field" value="" placeholder="Nombres" id="id_first_name" name="first_name">
            </div>

            <div class="form-group">
                <input type="text" class="form-control login-field" value="" placeholder="Apellidos" id="id_last_name" name="last_name">
            </div>


            <div class="form-group">
                <input type="text" class="form-control login-field" value="" placeholder="Identificación" id="id_documento" name="documento">
            </div>

            <div class="form-group">
                <select name="genero" id="id_genero" class="form-control login-field" >
                    <option value="M">Masculino</option>
                    <option value="F">Femenino</option>
                </select>
            </div>

            <div class="form-group">
                <input type="date" class="form-control login-field" value="" placeholder="Fecha de nacimiento" id="id_fnacimiento" name="fnacimiento">
            </div>

            <button type="submit" class="btn btn-primary btn-lg btn-block" style="background-color:#FFFF99; color: #000; border: 1px solid #000000 "> Registrar</button>
        </form>
        {% if form.errors %}
            {{ form.non_field_errors.as_ul|cut:"*" }}
            {{ form.username.errors.as_ul }}
            {{ form.password.errors.as_ul }}
        {% endif %}
    </div>

    <div id="backgroundaudio">
        <i class="fa fa-volume-up"></i>
        <audio autoplay="" controls="" loop="" preload="">
            <source src="{% static "../m.mp3" %}" type="audio/mpeg"/>
            Your browser does not support the audio element.
        </audio>
    </div>

{% endblock  %}